version: "3"

services:
  redis:
    image: registry.fedoraproject.org/f31/redis
    container_name: redis
    ports:
      - 6379:6379
    user: "123123"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - 8081:8081
    depends_on:
      - redis
    user: "123123"

  centosmsg:
    container_name: centosmsg
    build:
      context: .
      dockerfile: Dockerfile
    image: quay.io/packit/packit-service-centosmsg:dev
    command: listen-to-centos-messaging
    environment:
      LOG_LEVEL: DEBUG
      # MQTT_SUBTOPICS: pull-request
    volumes:
      - ./packit_service_centosmsg:/usr/local/lib/python3.8/site-packages/packit_service_centosmsg:ro,Z
      - ./secrets/centos-server-ca.cert:/secrets/centos-server-ca.cert:ro,Z
      - ./secrets/centos.cert:/secrets/centos.cert:ro,Z
    user: "123123"
